<?php
$z[0]=Array("field","",229,248);
$z[0][4]['name']="title";
$z[1]=Array("global","",249,275);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",316,338);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",378,429);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1518,1553);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1653,1681);
$z[5][4]['name']="picname";
$z[6]=Array("prenext","",1724,1752);
$z[6][4]['get']="preurl";
$z[7]=Array("prenext","",1817,1846);
$z[7][4]['get']="nexturl";
$z[8]=Array("field","",2299,2317);
$z[8][4]['name']="body";
$z[9]=Array("arclist","\r\n  <div class=\"caseBoxs\"> <a href=\"[field:arcurl/]\">\r\n    <p class=\"caseTitle\">FASHION<span>[field:title/]</span> </p>\r\n    <img class=\"over\" src=\"/skin/images/over.png\">\r\n    <div class=\"caseImg2\" style=\"background-image: url([field:picname/])\"></div>\r\n    <div class=\"caseBg\" style=\"background: #418dd9\"></div>\r\n    </a> </div>\r\n  ",2349,2745);
$z[9][4]['row']="3";
$z[9][4]['type']="image.";
$z[9][4]['typeid']="1";
$z[10]=Array("include","",2990,3027);
$z[10][4]['filename']="footer.htm";

?>