<?php
$z[0]=Array("global","",229,255);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",299,329);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",366,393);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",1543,1578);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n  <div class=\"caseBoxs\"> <a href=\"[field:arcurl/]\">\r\n    <p class=\"caseTitle\">WEDDING<span>[field:title/]</span> </p>\r\n    <img class=\"over\" src=\"/skin/images/over.png\">\r\n    <div class=\"caseImg2\" style=\"background-image: url([field:picname/])\"></div>\r\n    <div class=\"caseBg\" style=\"background: #71a787\"></div>\r\n    </a> </div>\r\n  ",1720,2100);
$z[4][4]['row']="6";
$z[4][4]['typei']="1";
$z[5]=Array("type","<a href=\"[field:typelink/]\"><b>查看我们的作品</b><span style=\"display: block;\"></span></a>",4367,4491);
$z[5][4]['typeid']="1";
$z[6]=Array("include","",5505,5542);
$z[6][4]['filename']="footer.htm";

?>