<?php
$z[0]=Array("field","",229,248);
$z[0][4]['name']="title";
$z[1]=Array("global","",249,275);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",316,345);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",385,443);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1532,1567);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n  <div class=\"caseBoxs\"> <a href=\"[field:arcurl/]\">\r\n    <p class=\"caseTitle\">WEDDING<span>[field:title/]</span> </p>\r\n    <img class=\"over\" src=\"/skin/images/over.png\">\r\n    <div class=\"caseImg2\" style=\"background-image: url([field:picname/])\"></div>\r\n    <div class=\"caseBg\" style=\"background: #71a787\"></div>\r\n    </a> </div>\r\n  ",1835,2205);
$z[5][4]['pagesize']="9";
$z[6]=Array("include","",2543,2580);
$z[6][4]['filename']="footer.htm";

?>